name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24
  - pyyaml
  - hydra-core=1.3.2
  - pip=23.3.1
  - pip:
      - mlflow==2.17.0
      - wandb==0.16.0
