name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pip=24.3.1
  - requests=2.32.3
  - scikit-learn=1.3.2
  - pandas=2.2.3
  - pip:
      - mlflow==2.18.0
      - wandb==0.16.0
      - git+https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components
